# Generated by Django 5.2.5 on 2025-08-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('twilio_call_sid', models.CharField(blank=True, max_length=100)),
                ('twilio_recording_sid', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=100)),
            ],
        ),
    ]
